# Generated by Django 2.0.3 on 2018-08-05 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/%Y/%m', verbose_name='照片')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
            ],
            options={
                'verbose_name': '历史事件',
                'verbose_name_plural': '历史事件',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='校长', max_length=50, verbose_name='职能名称')),
                ('cataglory', models.CharField(choices=[('上层领导', 'sc'), ('职能部门', 'zn'), ('教学部', 'jx')], default='zn', max_length=10)),
                ('up_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Part')),
            ],
            options={
                'verbose_name': '职能层',
                'verbose_name_plural': '职能层',
            },
        ),
        migrations.CreateModel(
            name='PartNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='无内容', max_length=50, verbose_name='姓名')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Part', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '职能部',
                'verbose_name_plural': '职能部',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='xxx', max_length=50, verbose_name='姓名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='person/%Y/%m', verbose_name='照片')),
                ('partnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PartNode', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
