# Generated by Django 2.0.3 on 2018-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180805_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未命名', max_length=100, verbose_name='名称')),
                ('left', models.IntegerField(default=0, verbose_name='左边距')),
                ('top', models.IntegerField(default=0, verbose_name='上边距')),
            ],
            options={
                'verbose_name': '景点',
                'verbose_name_plural': '景点',
            },
        ),
    ]
