# Generated by Django 2.0.3 on 2018-08-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_sight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sight/%Y/%m', verbose_name='照片')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sight', verbose_name='景点名称')),
            ],
            options={
                'verbose_name': '景点照片',
                'verbose_name_plural': '景点照片',
            },
        ),
    ]
