# Generated by Django 2.0.3 on 2018-08-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_sight_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='up_node',
        ),
    ]
