# Generated by Django 2.0.3 on 2018-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_part_up_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cataglory',
            field=models.CharField(choices=[('sc', '领导层'), ('zn', '职能部门'), ('jx', '教学部')], default='zn', max_length=10),
        ),
    ]
