# Generated by Django 2.0.3 on 2018-08-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_person_partnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='partnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PartNode', verbose_name='所属部门'),
        ),
    ]
