# Generated by Django 2.0.3 on 2018-08-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_person_partnode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnode',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='person',
            name='partnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Part', verbose_name='所属部门'),
        ),
    ]
