# Generated by Django 2.0.3 on 2018-08-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20180824_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnode',
            name='part',
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.DeleteModel(
            name='PartNode',
        ),
    ]
