# Generated by Django 2.0.3 on 2018-08-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180824_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='clickable',
            field=models.BooleanField(default=False, verbose_name='可点击'),
        ),
    ]
