# Generated by Django 2.0.3 on 2018-08-25 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='照片描述')),
                ('image', models.ImageField(upload_to='class/%Y/%m', verbose_name='照片')),
            ],
            options={
                'verbose_name': '班级风采',
                'verbose_name_plural': '班级风采',
            },
        ),
        migrations.CreateModel(
            name='ClassOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='班级介绍')),
                ('course', models.TextField(blank=True, null=True, verbose_name='课程设置')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='年级名')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=300, verbose_name='奖项描述')),
                ('p_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassOne', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '班级奖项',
                'verbose_name_plural': '班级奖项',
            },
        ),
        migrations.AddField(
            model_name='classone',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Grade', verbose_name='所属年级'),
        ),
        migrations.AddField(
            model_name='classimage',
            name='p_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassOne', verbose_name='所属班级'),
        ),
    ]
