# Generated by Django 2.0.3 on 2018-08-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20180826_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classimage',
            old_name='p_class',
            new_name='pclass',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='p_class',
            new_name='pclass',
        ),
    ]
